package itprocurementsystem;

/**
 * A JPanel keeps catalogue browsing and the Admin editor inside MainFrame.
 * @author alban-byamugisha
 */
public class CataloguePanel extends javax.swing.JPanel {

    /**
     * Creates new form CataloguePanel
     */
    public CataloguePanel() {
        initComponents();
        jPanelEditor.setVisible("Admin".equals(Session.getRole()));
        jLabeltitle.setText("Products and Services (UGX)");
        jTextAreaDescription.setLineWrap(true);
        jTextAreaDescription.setWrapStyleWord(true);
        jTableCatalogue.setModel(new javax.swing.table.DefaultTableModel(
                new String[]{"ID","Item name","Type","Category","Unit","Price (UGX)","Status"},0) {
            public boolean isCellEditable(int row, int column) { return false; }
        });
        // Named actions keep event code outside NetBeans-generated layout code.
        connect(jButtonSearch,"search"); connect(jButtonRefresh,"search");
        connect(jButtonAddItem,"add"); connect(jButtonUpdateItem,"update"); connect(jButtonClear,"clear");
        jTableCatalogue.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) { showSelected(); }
            }
        });
        try {
            java.util.ArrayList<Object[]> categories = new java.util.ArrayList<Object[]>();
            for (Category category : new CategoryDAO().getAllCategories()) {
                categories.add(new Object[]{category.getCategoryId(),category.getCategoryName()});
            }
            FormSupport.choices(jComboBoxCategory,categories,"Select category");
            clearEditor(); reload();
        } catch (Exception ex) { FormSupport.error(this,ex); }
    }

    // Keep complete rows, including descriptions which are not columns in the list.
    private java.util.ArrayList<Object[]> catalogueRows = new java.util.ArrayList<Object[]>();
    private void connect(javax.swing.JButton button, final String action) {
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                try {
                    if (action.equals("clear")) { clearEditor(); return; }
                    if (!action.equals("search")) {
                        int id = action.equals("add") ? 0 : FormSupport.selectedId(jTableCatalogue);
                        new CatalogueDAO().save(id,jTextFieldItemName.getText(),(String)jComboBoxType.getSelectedItem(),
                                FormSupport.choice(jComboBoxCategory),jTextFieldUnit.getText(),jTextAreaDescription.getText(),
                                jTextFieldPrice.getText(),jCheckBoxActive.isSelected());
                        clearEditor();
                    }
                    reload();
                } catch (Exception ex) { FormSupport.error(CataloguePanel.this,ex); }
            }
        });
    }
    private void reload() throws java.sql.SQLException {
        catalogueRows = new CatalogueDAO().list(jTextFieldSearch.getText(), "");
        FormSupport.fill(jTableCatalogue,catalogueRows);
    }
    private void clearEditor() {
        jTableCatalogue.clearSelection();
        jLabel3.setText("Select an item to view its specification.");
        jTextFieldItemName.setText(""); jTextFieldPrice.setText(""); jTextFieldUnit.setText("");
        jTextAreaDescription.setText(""); jCheckBoxActive.setSelected(false);
        jComboBoxType.setSelectedIndex(0); jComboBoxCategory.setSelectedIndex(0);
    }
    private void showSelected() {
        int index = jTableCatalogue.getSelectedRow();
        if (index < 0) { return; }
        Object[] row = catalogueRows.get(jTableCatalogue.convertRowIndexToModel(index));
        // Escape user text before putting it inside Swing's small HTML label.
        String details = (row[1] + ": " + row[7]).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");
        jLabel3.setText("<html><div style='width:500px'>" + details + "</div></html>");
        jTextFieldItemName.setText(row[1].toString()); jComboBoxType.setSelectedItem(row[2]);
        jTextFieldUnit.setText(row[4].toString()); jTextFieldPrice.setText(row[5].toString());
        jCheckBoxActive.setSelected("Active".equals(row[6])); jTextAreaDescription.setText(row[7].toString());
        for (int i=1; i<jComboBoxCategory.getItemCount(); i++) {
            if (jComboBoxCategory.getItemAt(i).startsWith(row[8] + " - ")) { jComboBoxCategory.setSelectedIndex(i); break; }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabeltitle = new javax.swing.JLabel();
        jLabelSearch = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonRefresh = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCatalogue = new javax.swing.JTable();
        jPanelEditor = new javax.swing.JPanel();
        jLabelItemName = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jButtonAddItem = new javax.swing.JButton();
        jButtonUpdateItem = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jTextFieldItemName = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jLabelUnit = new javax.swing.JLabel();
        jTextFieldUnit = new javax.swing.JTextField();
        jCheckBoxActive = new javax.swing.JCheckBox();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jButton3.setText("");

        jLabel8.setText("");

        jButton7.setText("");

        jTextField6.setText("");

        jLabel12.setText("");

        jLabeltitle.setText("Products and Services");

        jLabelSearch.setText("Search");

        jButtonRefresh.setText("Refresh");

        jButtonSearch.setText("Search");

        jTableCatalogue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Type", "Category", "Unit", "Price(UGX)", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCatalogue);

        jLabelItemName.setText("Item name");

        jLabelCategory.setText("Category");

        jLabelPrice.setText("Price (UGX)");

        jLabel7.setText("Description / specification");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescription);

        jButtonAddItem.setText("Add Item");

        jButtonUpdateItem.setText("Update Selected");
        jButtonUpdateItem.addActionListener(this::jButtonUpdateItemActionPerformed);

        jButtonClear.setText("Clear");

        jLabelType.setText("Type");

        jLabelUnit.setText("Unit");

        jCheckBoxActive.setText("Active");

        jComboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select category" }));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type", "Equipment", "Service" }));

        javax.swing.GroupLayout jPanelEditorLayout = new javax.swing.GroupLayout(jPanelEditor);
        jPanelEditor.setLayout(jPanelEditorLayout);
        jPanelEditorLayout.setHorizontalGroup(
            jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel7)
                    .addGroup(jPanelEditorLayout.createSequentialGroup()
                        .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelItemName)
                            .addComponent(jLabelCategory)
                            .addComponent(jLabelPrice))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxCategory, 0, 171, Short.MAX_VALUE)
                            .addComponent(jTextFieldItemName)
                            .addComponent(jTextFieldPrice))
                        .addGap(62, 62, 62)
                        .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEditorLayout.createSequentialGroup()
                                .addComponent(jLabelUnit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldUnit))
                            .addGroup(jPanelEditorLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jCheckBoxActive)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelEditorLayout.createSequentialGroup()
                                .addComponent(jLabelType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanelEditorLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jButtonAddItem)
                .addGap(58, 58, 58)
                .addComponent(jButtonUpdateItem)
                .addGap(44, 44, 44)
                .addComponent(jButtonClear)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanelEditorLayout.setVerticalGroup(
            jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelItemName)
                    .addComponent(jTextFieldItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelType)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCategory)
                        .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUnit)
                        .addComponent(jTextFieldUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxActive))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddItem)
                    .addComponent(jButtonUpdateItem)
                    .addComponent(jButtonClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Select an item to view its specification.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSearch)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabeltitle)
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabeltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearch)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jPanelEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateItemActionPerformed
        // Updating is handled by connect(jButtonUpdateItem, "update") in the constructor.
    }//GEN-LAST:event_jButtonUpdateItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdateItem;
    private javax.swing.JCheckBox jCheckBoxActive;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelItemName;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelUnit;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JPanel jPanelEditor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCatalogue;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldItemName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldUnit;
    // End of variables declaration//GEN-END:variables
}
