/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itprocurementsystem;

/**
 * We use a JPanel because department management belongs inside MainFrame.
 * It groups the related controls without opening another window.
 * MainFrame provides the title bar and navigation for this panel.
 *
 * @author alban-byamugisha
 */
public class DepartmentPanel extends javax.swing.JPanel {
    // The DAO handles validation and SQL; the form handles display.
    private final ManagementDAO management = new ManagementDAO();


    /**
     * Creates new form DepartmentPanel
     */
    public DepartmentPanel() {
        // Build the controls and layout saved in NetBeans Design view.
        initComponents();
        // Run this action when the user clicks the button.
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                try { reload(); }
                catch (Exception ex) { FormSupport.error(null, ex); }
            }
        });
        // Run this action when the user clicks the button.
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                try { jTableDepartments.clearSelection(); jTextFieldDepartmentName.setText(""); }
                catch (Exception ex) { FormSupport.error(null, ex); }
            }
        });
        // Run this action when the user clicks the button.
        jButtonAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                try { saveDepartment(0); }
                catch (Exception ex) { FormSupport.error(null, ex); }
            }
        });
        // Run this action when the user clicks the button.
        jButtonUpdateDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent event) {
                try { saveDepartment(FormSupport.selectedId(jTableDepartments)); }
                catch (Exception ex) { FormSupport.error(null, ex); }
            }
        });
        // Show the selected row in the editing fields.
        jTableDepartments.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) { jTextFieldDepartmentName.setText(FormSupport.cell(jTableDepartments,1).toString()); jLabelSelectedDepartment.setText("Selected department: " + FormSupport.cell(jTableDepartments,1)); }
            }
        });
        reload();

    }

    // Refresh the table so it reflects the database, not an unsaved field.
    private void reload() {
        try { FormSupport.fill(jTableDepartments, management.departments()); jLabelCount.setText("Departments: " + jTableDepartments.getRowCount()); }
        catch (Exception ex) { FormSupport.error(this, ex); }
    }
    private void saveDepartment(int id) throws java.sql.SQLException {
        management.saveDepartment(id, jTextFieldDepartmentName.getText()); reload(); jTextFieldDepartmentName.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelDepartmentName = new javax.swing.JLabel();
        jTextFieldDepartmentName = new javax.swing.JTextField();
        jButtonAddDepartment = new javax.swing.JButton();
        jButtonUpdateDepartment = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDepartments = new javax.swing.JTable();
        jLabelSelectedDepartment = new javax.swing.JLabel();
        jLabelCount = new javax.swing.JLabel();



        jLabelTitle.setText("Department Management");

        jLabelDepartmentName.setText("Department name:");

        jButtonAddDepartment.setText("Add Department");

        jButtonUpdateDepartment.setText("Update Selected");

        jButtonClear.setText("Clear");

        jButtonRefresh.setText("Refresh");

        jTableDepartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department ID", "Department Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDepartments);

        jLabelSelectedDepartment.setText("Selected department: None");

        jLabelCount.setText("Departments: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDepartmentName)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDepartmentName))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSelectedDepartment)
                            .addComponent(jLabelCount))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddDepartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUpdateDepartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jButtonClear)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRefresh)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDepartmentName)
                    .addComponent(jTextFieldDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddDepartment)
                    .addComponent(jButtonUpdateDepartment)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSelectedDepartment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDepartment;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonUpdateDepartment;
    private javax.swing.JLabel jLabelCount;
    private javax.swing.JLabel jLabelDepartmentName;
    private javax.swing.JLabel jLabelSelectedDepartment;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDepartments;
    private javax.swing.JTextField jTextFieldDepartmentName;
    // End of variables declaration//GEN-END:variables
}
