/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itprocurementsystem;

// JOptionPane displays a short message when the user clicks Login.
import javax.swing.JOptionPane;

// SQLException lets the form handle database problems separately from incorrect credentials.
import java.sql.SQLException;

/**
 *
 * @author alban-byamugisha
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        // Create the labels, input fields and button arranged in Design view.
        initComponents();

        // Center this window on the screen after its size has been set.
        // null means we center it on the screen, rather than beside another window.
        setLocationRelativeTo(null);

        // Remove the designer's sample password so the user starts with an empty field.
        jPasswordFieldPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setText("IT PROCUREMENT REQUEST SYSTEM");

        jLabelUsername.setText("Username:");

        jLabelPassword.setText("Password:");

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(this::jButtonLoginActionPerformed);

        jPasswordFieldPassword.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsername)
                            .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButtonLogin)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // Read the username. trim() removes spaces from its beginning and end.
        String username = jTextFieldUsername.getText().trim();

        // An empty username, or one containing only spaces, is not allowed.
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter your username.",
                    "Missing Username",
                    JOptionPane.WARNING_MESSAGE);

            // Move the cursor to the username field and stop this button action.
            jTextFieldUsername.requestFocusInWindow();
            return;
        }

        // getPassword() returns the typed characters; length tells us how many.
        // We do not trim passwords because spaces can be part of a password.
        if (jPasswordFieldPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Please enter your password.",
                    "Missing Password",
                    JOptionPane.WARNING_MESSAGE);

            // Move the cursor to the password field and wait for the user to fill it.
            jPasswordFieldPassword.requestFocusInWindow();
            return;
        }

        // Read the password without trimming it because spaces may be intentional.
        String password = new String(jPasswordFieldPassword.getPassword());

        try {
            // Create a UserDAO object and ask it to check the account in the database.
            UserDAO userDAO = new UserDAO();
            boolean correctLogin = userDAO.checkLogin(username, password);

            if (correctLogin) {
                // Authentication now works. We will build the next screen in a later step.
                JOptionPane.showMessageDialog(this,
                        "Login successful! The next screen will be added in our next step.",
                        "Login",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Use the same message for a wrong username and a wrong password.
                JOptionPane.showMessageDialog(this,
                        "Incorrect username or password.",
                        "Login Failed",
                        JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            // A database problem is different from incorrect login details.
            JOptionPane.showMessageDialog(this,
                    "Could not check your account. Check that XAMPP MySQL is running\n"
                    + "and that the database and JDBC connection settings are correct.",
                    "Database Problem",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IllegalStateException ex) {
            // Avoid showing a technical error if password hashing is unavailable.
            JOptionPane.showMessageDialog(this,
                    "Password checking is unavailable. Please check your Java installation.",
                    "Login Problem",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            // Clear the visible password after every attempt, whether it succeeds or fails.
            jPasswordFieldPassword.setText("");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
