// Place this class in the itprocurementsystem package so related application classes share one
// namespace.
package itprocurementsystem;

// JOptionPane displays a short message when the user clicks Login.
// Import JOptionPane for standard Swing message, confirmation and input dialogs.
import javax.swing.JOptionPane;

// SQLException lets the form handle database problems separately from incorrect credentials.
// Import SQLException for database errors that can be caught or passed to a caller.
import java.sql.SQLException;

/**
 * A JFrame is used because the login screen needs its own window.
 * It can appear before the main window and has a title bar and close button.
 * Extending JFrame gives this class the basic features of a Swing window.
 *
 * @author alban-byamugisha
 */
// Define LoginFrame as a JFrame: it owns a top-level window with a title bar and window controls.
public class LoginFrame extends javax.swing.JFrame {
    
    // Only this class accesses this field directly. Declare logger with type java.util.logging.Logger. Its
    // initial value is `java.util.logging.Logger.getLogger(LoginFrame.class.getName())`. This field is
    // shared by all instances of the class. The reference or value cannot be reassigned after
    // initialisation.
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    // Construct this object and initialise its fields or controls from the supplied starting values; a
    // constructor has no return type.
    public LoginFrame() {
        // Create the labels, input fields and button arranged in Design view.
        // Create the controls and apply the layout stored by NetBeans before reading or changing any of those
        // controls.
        initComponents();
        // Registration is available before login; it creates Requester accounts only.
        // Connect this control to its actionPerformed callback, which runs when an action is raised.
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            // Handle the action event raised by the control connected to this listener.
            // Ask the compiler to verify that this method overrides an inherited method.
            @Override
            public void actionPerformed(java.awt.event.ActionEvent event) {
                // Set whether new RegisterFrame() is shown using true.
                new RegisterFrame().setVisible(true);
                // Close this login window so returning from registration opens only one.
                // Close this window and release its native resources without clearing other application windows.
                dispose();
            }
        });

        // Password recovery opens before login, so it has its own JFrame.
        // Connect this control to its actionPerformed callback, which runs when an action is raised.
        jButtonForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            // Handle the action event raised by the control connected to this listener.
            public void actionPerformed(java.awt.event.ActionEvent event) {
                // Set whether new ForgotPasswordFrame() is shown using true.
                new ForgotPasswordFrame().setVisible(true);
                // Close this window and release its native resources without clearing other application windows.
                dispose();
            }
        });
        // Center this window on the screen after its size has been set.
        // null means the window is centred on the screen, rather than beside another window.
        // Centre this window on the screen; null means there is no parent window to centre against.
        setLocationRelativeTo(null);

        // Remove the designer's sample password so the user starts with an empty field.
        // Set the text displayed by jPasswordFieldPassword to empty text.
        jPasswordFieldPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * Horizontal groups control widths and left/right positions; vertical groups control heights.
     * LEADING aligns starts, TRAILING aligns ends, and BASELINE aligns text baselines.
     * PREFERRED_SIZE uses the component's preferred size; DEFAULT_SIZE asks the layout for a default.
     * Short.MAX_VALUE permits a large flexible size; it is not the actual window size.
     * Comments within the generated method may be replaced when Design view regenerates it.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Create and arrange the controls described by the matching NetBeans .form file. Design view
    // regenerates this method.
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Set jLabelTitle from the following operation: create a non-editable text or image display.
        jLabelTitle = new javax.swing.JLabel();
        // Set jLabelUsername from the following operation: create a non-editable text or image display.
        jLabelUsername = new javax.swing.JLabel();
        // Set jLabelPassword from the following operation: create a non-editable text or image display.
        jLabelPassword = new javax.swing.JLabel();
        // Set jButtonLogin from the following operation: create a clickable action button.
        jButtonLogin = new javax.swing.JButton();
        // Set jTextFieldUsername from the following operation: create a single-line text input.
        jTextFieldUsername = new javax.swing.JTextField();
        // Set jPasswordFieldPassword from the following operation: create an input that masks password
        // characters.
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        // Set jButtonRegister from the following operation: create a clickable action button.
        jButtonRegister = new javax.swing.JButton();
        // Set jButtonForgotPassword from the following operation: create a clickable action button.
        jButtonForgotPassword = new javax.swing.JButton();

        // Choose what the window close button does: EXIT_ON_CLOSE stops the application; DISPOSE_ON_CLOSE
        // closes only this window.
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Set the text displayed by jLabelTitle to "IT Procurement Request System".
        jLabelTitle.setText("IT Procurement Request System");

        // Set the text displayed by jLabelUsername to "Username:".
        jLabelUsername.setText("Username:");

        // Set the text displayed by jLabelPassword to "Password:".
        jLabelPassword.setText("Password:");

        // Set the text displayed by jButtonLogin to "Login".
        jButtonLogin.setText("Login");
        // Connect this control to its actionPerformed callback, which runs when an action is raised.
        jButtonLogin.addActionListener(this::jButtonLoginActionPerformed);

        // Set the text displayed by jButtonRegister to "Create Account".
        jButtonRegister.setText("Create Account");

        // Set the text displayed by jButtonForgotPassword to "Forgot Password ?".
        jButtonForgotPassword.setText("Forgot Password ?");

        // Declare layout with type javax.swing.GroupLayout. Create a layout manager describing horizontal and
        // vertical arrangements separately.
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        // Assign the supplied layout manager to getContentPane() to control child-component positions and
        // sizes.
        getContentPane().setLayout(layout);
        // Define the left-to-right arrangement and widths; the vertical group separately controls heights.
        layout.setHorizontalGroup(
            // Start a parallel group whose children occupy the same region on this axis, using the selected
            // alignment.
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            // Nest a sequential group to place controls one after another.
            .addGroup(layout.createSequentialGroup()
                // Nest a parallel group so controls share this horizontal or vertical region.
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    // Nest a sequential group to place controls one after another.
                    .addGroup(layout.createSequentialGroup()
                        // Leave the stated gap in this layout; multiple values specify minimum, preferred and maximum spacing.
                        .addGap(82, 82, 82)
                        // Place jLabelTitle in this layout group; any following size arguments give minimum, preferred and
                        // maximum sizes.
                        .addComponent(jLabelTitle))
                    // Nest a sequential group to place controls one after another.
                    .addGroup(layout.createSequentialGroup()
                        // Leave the stated gap in this layout; multiple values specify minimum, preferred and maximum spacing.
                        .addGap(19, 19, 19)
                        // Nest a parallel group so controls share this horizontal or vertical region.
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            // Place jButtonLogin in this layout group; any following size arguments give minimum, preferred and
                            // maximum sizes.
                            .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            // Nest a parallel group so controls share this horizontal or vertical region.
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                // Place jLabelUsername in this layout group; any following size arguments give minimum, preferred and
                                // maximum sizes.
                                .addComponent(jLabelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                // Place jLabelPassword in this layout group; any following size arguments give minimum, preferred and
                                // maximum sizes.
                                .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        // Insert the look-and-feel's recommended spacing between neighbouring controls.
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        // Nest a parallel group so controls share this horizontal or vertical region.
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            // Nest a parallel group so controls share this horizontal or vertical region.
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                // Place jTextFieldUsername in this layout group; any following size arguments give minimum, preferred
                                // and maximum sizes.
                                .addComponent(jTextFieldUsername)
                                // Place jPasswordFieldPassword in this layout group; any following size arguments give minimum,
                                // preferred and maximum sizes.
                                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                            // Place jButtonRegister in this layout group; any following size arguments give minimum, preferred and
                            // maximum sizes.
                            .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    // Nest a sequential group to place controls one after another.
                    .addGroup(layout.createSequentialGroup()
                        // Leave the stated gap in this layout; multiple values specify minimum, preferred and maximum spacing.
                        .addGap(67, 67, 67)
                        // Place jButtonForgotPassword in this layout group; any following size arguments give minimum,
                        // preferred and maximum sizes.
                        .addComponent(jButtonForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                // Leave spacing between the group and its enclosing container edge.
                .addContainerGap(65, Short.MAX_VALUE))
        );
        // Define the top-to-bottom arrangement and heights; the horizontal group separately controls widths.
        layout.setVerticalGroup(
            // Start a parallel group whose children occupy the same region on this axis, using the selected
            // alignment.
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            // Nest a sequential group to place controls one after another.
            .addGroup(layout.createSequentialGroup()
                // Leave the stated gap in this layout; multiple values specify minimum, preferred and maximum spacing.
                .addGap(18, 18, 18)
                // Place jLabelTitle in this layout group; any following size arguments give minimum, preferred and
                // maximum sizes.
                .addComponent(jLabelTitle)
                // Leave the stated gap in this layout; multiple values specify minimum, preferred and maximum spacing.
                .addGap(35, 35, 35)
                // Nest a parallel group so controls share this horizontal or vertical region.
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    // Place jLabelUsername in this layout group; any following size arguments give minimum, preferred and
                    // maximum sizes.
                    .addComponent(jLabelUsername)
                    // Place jTextFieldUsername in this layout group; any following size arguments give minimum, preferred
                    // and maximum sizes.
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                // Leave the stated gap in this layout; multiple values specify minimum, preferred and maximum spacing.
                .addGap(54, 54, 54)
                // Nest a parallel group so controls share this horizontal or vertical region.
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    // Place jLabelPassword in this layout group; any following size arguments give minimum, preferred and
                    // maximum sizes.
                    .addComponent(jLabelPassword)
                    // Place jPasswordFieldPassword in this layout group; any following size arguments give minimum,
                    // preferred and maximum sizes.
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                // Insert the look-and-feel's recommended spacing between neighbouring controls.
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                // Nest a parallel group so controls share this horizontal or vertical region.
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    // Place jButtonLogin in this layout group; any following size arguments give minimum, preferred and
                    // maximum sizes.
                    .addComponent(jButtonLogin)
                    // Place jButtonRegister in this layout group; any following size arguments give minimum, preferred and
                    // maximum sizes.
                    .addComponent(jButtonRegister))
                // Insert the look-and-feel's recommended spacing between neighbouring controls.
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                // Place jButtonForgotPassword in this layout group; any following size arguments give minimum,
                // preferred and maximum sizes.
                .addComponent(jButtonForgotPassword)
                // Leave spacing between the group and its enclosing container edge.
                .addContainerGap())
        );

        // Calculate the window size from the preferred sizes of its controls and layout.
        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Handle the action event from jButtonLogin; any statements below run when that action is raised.
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // Read the username. trim() removes spaces from its beginning and end.
        // Declare username to hold text. Remove spaces and other trim characters from both ends of
        // jTextFieldUsername.getText() without changing text in the middle.
        String username = jTextFieldUsername.getText().trim();

        // An empty username, or one containing only spaces, is not allowed.
        // Continue with this branch when (username is empty).
        if (username.isEmpty()) {
            // Display the supplied message in a Swing dialog, using the parent, title and message style when
            // provided.
            JOptionPane.showMessageDialog(this,
                    "Please enter your username.",
                    "Missing Username",
                    JOptionPane.WARNING_MESSAGE);

            // Move the cursor to the username field and stop this button action.
            // Move keyboard focus to jTextFieldUsername so the next typing goes to that control.
            jTextFieldUsername.requestFocusInWindow();
            // Stop this method here; no further statements in this call are executed.
            return;
        }

        // getPassword() returns the typed characters; length gives the number of characters.
        // The application does not trim passwords because spaces can be part of a password.
        // Continue with this branch when (jPasswordFieldPassword.getPassword().length equals 0).
        if (jPasswordFieldPassword.getPassword().length == 0) {
            // Display the supplied message in a Swing dialog, using the parent, title and message style when
            // provided.
            JOptionPane.showMessageDialog(this,
                    "Please enter your password.",
                    "Missing Password",
                    JOptionPane.WARNING_MESSAGE);

            // Move the cursor to the password field and wait for the user to fill it.
            // Move keyboard focus to jPasswordFieldPassword so the next typing goes to that control.
            jPasswordFieldPassword.requestFocusInWindow();
            // Stop this method here; no further statements in this call are executed.
            return;
        }

        // Read the password without trimming it because spaces may be intentional.
        // Declare password to hold text. Create an immutable text value from the supplied characters.
        String password = new String(jPasswordFieldPassword.getPassword());

        // Attempt these operations; the following catch or finally blocks handle failures or cleanup.
        try {
            // Create a UserDAO object and ask it to check the account in the database.
            // Declare userDAO with type UserDAO. Create a UserDAO object using the supplied constructor values.
            UserDAO userDAO = new UserDAO();
            // Declare correctLogin to hold a true-or-false flag. Verify the entered password hash against the
            // saved account and start a session only after a match.
            boolean correctLogin = userDAO.checkLogin(username, password);

            // Continue with this branch when (correctLogin).
            if (correctLogin) {
                // Cancel/close signs out; MainFrame opens only after the required change succeeds.
                // Continue with this branch when (Session.mustChangePassword() and not
                // PasswordChangeDialog.show(this)).
                // Stop this method here; no further statements in this call are executed.
                if (Session.mustChangePassword() && !PasswordChangeDialog.show(this)) { return; }
                // Tell the user that the database accepted their login details.
                // Display the supplied message in a Swing dialog, using the parent, title and message style when
                // provided.
                JOptionPane.showMessageDialog(this,
                        "Welcome, " + Session.getFullName() + "!",
                        "Login Successful",
                        JOptionPane.INFORMATION_MESSAGE);

                // Open the main window, which reads the user's details from Session.
                // Declare mainFrame with type MainFrame. Create a MainFrame object using the supplied constructor
                // values.
                MainFrame mainFrame = new MainFrame();
                // Set whether mainFrame is shown using true.
                mainFrame.setVisible(true);

                // Close the login window after the main window has opened.
                // Close this window and release its native resources without clearing other application windows.
                dispose();
            } else {
                // Use the same message for a wrong username and a wrong password.
                // Display the supplied message in a Swing dialog, using the parent, title and message style when
                // provided.
                JOptionPane.showMessageDialog(this,
                        "Incorrect username or password.",
                        "Login Failed",
                        JOptionPane.WARNING_MESSAGE);
            }
        // Handle SQLException ex from the preceding try block so the failure follows the recovery steps below.
        } catch (SQLException ex) {
            // A database problem is different from incorrect login details.
            // Display the supplied message in a Swing dialog, using the parent, title and message style when
            // provided.
            JOptionPane.showMessageDialog(this,
                    "Could not check your account. Check that XAMPP MySQL is running\n"
                    + "and that the database and JDBC connection settings are correct.",
                    "Database Problem",
                    JOptionPane.ERROR_MESSAGE);
        // Handle IllegalStateException ex from the preceding try block so the failure follows the recovery
        // steps below.
        } catch (IllegalStateException ex) {
            // Avoid showing a technical error if password hashing is unavailable.
            // Display the supplied message in a Swing dialog, using the parent, title and message style when
            // provided.
            JOptionPane.showMessageDialog(this,
                    "Password checking is unavailable. Please check your Java installation.",
                    "Login Problem",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            // Clear the visible password after every attempt, whether it succeeds or fails.
            // Set the text displayed by jPasswordFieldPassword to empty text.
            jPasswordFieldPassword.setText("");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    // Provide the entry point used when this Java class is launched directly.
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        // Attempt these operations; the following catch or finally blocks handle failures or cleanup.
        try {
            // Process each entry in javax.swing.UIManager.getInstalledLookAndFeels() in turn, referring to the
            // current entry as info.
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                // Continue with this branch when ("Nimbus".equals(info.getName())).
                if ("Nimbus".equals(info.getName())) {
                    // Apply the chosen installed Swing appearance to subsequently created controls.
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    // Leave the current loop once the required result has been found.
                    break;
                }
            }
        // Handle ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex from the
        // preceding try block so the failure follows the recovery steps below.
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            // Record the exception at SEVERE level so a look-and-feel setup failure can be diagnosed.
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // Schedule this work on Swing's event dispatch thread so window updates run on the UI thread.
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Only this class accesses this field directly. Declare jButtonForgotPassword with type
    // javax.swing.JButton. Java initially uses null for this object reference.
    private javax.swing.JButton jButtonForgotPassword;
    // Only this class accesses this field directly. Declare jButtonLogin with type javax.swing.JButton.
    // Java initially uses null for this object reference.
    private javax.swing.JButton jButtonLogin;
    // Only this class accesses this field directly. Declare jButtonRegister with type javax.swing.JButton.
    // Java initially uses null for this object reference.
    private javax.swing.JButton jButtonRegister;
    // Only this class accesses this field directly. Declare jLabelPassword with type javax.swing.JLabel.
    // Java initially uses null for this object reference.
    private javax.swing.JLabel jLabelPassword;
    // Only this class accesses this field directly. Declare jLabelTitle with type javax.swing.JLabel. Java
    // initially uses null for this object reference.
    private javax.swing.JLabel jLabelTitle;
    // Only this class accesses this field directly. Declare jLabelUsername with type javax.swing.JLabel.
    // Java initially uses null for this object reference.
    private javax.swing.JLabel jLabelUsername;
    // Only this class accesses this field directly. Declare jPasswordFieldPassword with type
    // javax.swing.JPasswordField. Java initially uses null for this object reference.
    private javax.swing.JPasswordField jPasswordFieldPassword;
    // Only this class accesses this field directly. Declare jTextFieldUsername with type
    // javax.swing.JTextField. Java initially uses null for this object reference.
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
