/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itprocurementsystem;

/**
 *
 * @author alban-byamugisha
 */
public class ServiceCompletionPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServiceCompletionPanel
     */
    public ServiceCompletionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelSelectReqeust = new javax.swing.JLabel();
        jComboBoxRequest = new javax.swing.JComboBox<>();
        jButtonLoadDetails = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jLabelProvider = new javax.swing.JLabel();
        jLabelRequestedServices = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServiceItems = new javax.swing.JTable();
        jLabelWorkStatus = new javax.swing.JLabel();
        jComboBoxWorkStatus = new javax.swing.JComboBox<>();
        jLabelCompletionDate = new javax.swing.JLabel();
        jTextFieldCompletionDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaWorkNotes = new javax.swing.JTextArea();
        jButtonClear = new javax.swing.JButton();
        jButtonSaveProgress = new javax.swing.JButton();
        jLabelHint = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jLabelTitle.setText("Service Completion");

        jLabelSelectReqeust.setText("Select Request:");

        jComboBoxRequest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select request" }));

        jButtonLoadDetails.setText("Load Details");

        jButtonRefresh.setText("Refresh");

        jLabelProvider.setText("Provider: Select a request");

        jLabelRequestedServices.setText("Requested Services:");

        jTableServiceItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Description", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableServiceItems);

        jLabelWorkStatus.setText("Work Status:");

        jComboBoxWorkStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select status", "Not Started", "In Progress", "Completed" }));

        jLabelCompletionDate.setText("Completion date (YYYY-MM-DD):");

        jLabel1.setText("Work notes:");

        jTextAreaWorkNotes.setColumns(20);
        jTextAreaWorkNotes.setRows(5);
        jScrollPane2.setViewportView(jTextAreaWorkNotes);

        jButtonClear.setText("Clear");

        jButtonSaveProgress.setText("Save Progress");

        jLabelHint.setText("Enter a completion date only when the service is completed.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelTitle)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelSelectReqeust)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(jButtonLoadDetails)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonRefresh))
                        .addComponent(jLabelProvider)
                        .addComponent(jLabelRequestedServices)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelWorkStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxWorkStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCompletionDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCompletionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButtonClear)
                .addGap(87, 87, 87)
                .addComponent(jButtonSaveProgress))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelHint))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectReqeust)
                    .addComponent(jComboBoxRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLoadDetails)
                    .addComponent(jButtonRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProvider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRequestedServices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWorkStatus)
                    .addComponent(jComboBoxWorkStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCompletionDate)
                    .addComponent(jTextFieldCompletionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonSaveProgress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHint)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonLoadDetails;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSaveProgress;
    private javax.swing.JComboBox<String> jComboBoxRequest;
    private javax.swing.JComboBox<String> jComboBoxWorkStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCompletionDate;
    private javax.swing.JLabel jLabelHint;
    private javax.swing.JLabel jLabelProvider;
    private javax.swing.JLabel jLabelRequestedServices;
    private javax.swing.JLabel jLabelSelectReqeust;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelWorkStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableServiceItems;
    private javax.swing.JTextArea jTextAreaWorkNotes;
    private javax.swing.JTextField jTextFieldCompletionDate;
    // End of variables declaration//GEN-END:variables
}
